### ISSUE TITLE
Why is this happening

### ISSUE THREAD

**Issue by Jayol1234** [WICG/private-network-access#112]
When I change apn protocol to ipv4, I then receive text messages. Otherwise, they are coming through. What has changed? Please stop blocking my text messages. This is unacceptable

**Comment by Jayol1234** [comment]
Block insecure private network requests.
Prevents non-secure contexts from making sub-resource requests to more-private IP addresses. An IP address IP1 is more private than IP2 if 1) IP1 is localhost and IP2 is not, or 2) IP1 is private and IP2 is public. This is a first step towards full enforcement of CORS-RFC1918: https://wicg.github.io/cors-rfc1918 – Mac, Windows, Linux, Chrome OS, Android

#block-insecure-private-network-requests

Default

This is causing problem. What do you suggest?

**Comment by johnathan79717** [comment]
Hi Jayol1234.  This repo is for specification discussions but your issue seems like a bug report.  If you think Chrome is blocking requests when it shouldn't (e.g. mis-identifying requests as private network access), please create an issue on https://crbug.com.  Attaching a [NetLog dump](https://www.chromium.org/for-testers/providing-network-details/) to the created issue can help us debug a lot.
