### ISSUE TITLE
Update Integration with WebSockets

### ISSUE THREAD

**Issue by fred-wang** [WICG/private-network-access#55]
From https://wicg.github.io/private-network-access/#integration-websockets:

>  The establish a WebSocket connection algorithm should be adjusted ...
> Further, the same algorithm should be adjusted to check the response for an opt-in. For instance, the following could be executed after the current step 12:

There is currently no step 12 in https://fetch.spec.whatwg.org/#concept-websocket-establish

**Comment by letitz** [comment]
Yes, I've been meaning to come back to the spec and these parts in particular, since they are out of date. As you suggest in #54, I think being more specific in English terms ("before frobnicating foo", "after reticulating splines") about the place where we want to hook would help keep this more relevant and up-to-date until a proper PR can be drafted against Fetch/HTML/WebSocket specs.
