### ISSUE TITLE
Question: use cases for activating PNA only for some (and not all) allowed origins?

### ISSUE THREAD

**Issue by jub0bs** [WICG/private-network-access#84]
Some CORS-middleware libraries have already added support for PNA. However, some of them (such as https://github.com/rs/cors) only allow their users to enable a blanket PNA policy for all allowed origins.

As I'm working on a principled CORS middleware for Go, I'm wondering whether my users will want a more fine-grained approach that would allow them to enable PNA for some of their allowed origins and not for others. For instance, will some people want to

- allow origin `https://foo.com` even from less private networks (e.g. with PNA), and
- allow origin `https://bar.com` _but only_ from as private networks (e.g. without PNA)?

Do you anticipate such use cases?

**Comment by letitz** [comment]
For IoT setups / home devices, I mostly expect servers will wish to allow a single origin, or a small list, *with* PNA, and none otherwise. However, it might be that some resources on the server are truly public and would be fine with allowing any origin *with or without* PNA.

For a single given path though, I don't expect the level of granularity that you envision, simply because `https://bar.com` should be the same entity, regardless of where it sits on the network. After all, it passed certificate checks.

If PNA did not restrict requests to secure contexts, then there would be a risk of impersonation, and it might be good to allow insecure origins only *without* PNA, for example.
